#/run/numberOfThreads 1
/run/initialize

/vis/open OGLSQt 600x600-0+0
#/vis/open OGL 
#/vis/viewer/set/style wireframe

/vis/drawVolume
/vis/viewer/set/viewpointVector 1 1 1
/vis/viewer/set/autoRefresh true

#/tracking/storeTrajectory 0
#/vis/disable  

/vis/scene/add/trajectories smooth
#/vis/scene/endOfEventAction accumulate -1
#/vis/scene/endOfEventAction clear
/vis/scene/add/scale 10 cm
/vis/scene/add/axes
/vis/scene/add/eventID

/run/beamOn 10
